language: ruby
rvm:
  - 2.1

before_script:
  - chmod +x ./script/cibuild

script: ./script/cibuild

branches:
  only:
    - gh-pages
    - /pages-(.*)/ # test every branch that starts with pages

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

